### ISSUE TITLE
Music not playing 

### ISSUE THREAD

**Issue by SloppierKitty7** [Brayzure/DiscordMusic#2]
$ node bot.js
LOG [11:57:13] Music Bot is ready to go!
LOG [11:57:16] Command !join invoked by SloppierKitty7
STATUS [11:57:16] OK
LOG [11:57:17] playNext() called!
LOG [11:57:17] Created interval()
LOG [11:57:17] Playing AMV - Orion - Bestamvsofalltime Anime MV ♫
LOG [11:57:20] Command !add invoked by SloppierKitty7
STATUS [11:57:20] OK
LOG [11:57:23] Command !play invoked by SloppierKitty7
STATUS [11:57:23] OK
LOG [11:57:24] Advancing song automatically!
LOG [11:57:24] playNext() called!
LOG [11:57:24] Playing AMV - Orion - Bestamvsofalltime Anime MV ♫
LOG [11:57:29] No more songs!
LOG [11:57:29] Destroyed interval()!

i think it has something to do with ffmpg on windows

**Comment by Brayzure** [comment]
You're probably right, try following [this guide](http://adaptivesamples.com/how-to-install-ffmpeg-on-windows/) to install it. Also while you're at it, check to see if Opus installed correctly. Go to dir\node_modules\discord.js\node_modules. There should be five modules installed there, one of which is node-opus.

**Comment by Brayzure** [comment]
Any feedback?

**Comment by SloppierKitty7** [comment]
@Brayzure sorry have not had the time to test it but will try to get back to you by the end of the week

**Comment by Brayzure** [comment]
Going to close this issue for now, feel free to open another one if my suggestion does not work.

**Comment by SloppierKitty7** [comment]
@Brayzure i've installed FFmpeg as the guide showed but when i try to install node-opus i get 

https://i.gyazo.com/2075780a831fbf5d3961f061ef69a06d.png

**Comment by Brayzure** [comment]
It appears that you do not have `python.exe` in your Path. [Try this](http://www.tutorialspoint.com/python/python_environment.htm) and let me know how it goes.
