### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by otaviomad** [Brayzure/DiscordMusic#3]
This is pretty much the only bot that works and is pretty great but: 

When you try removing something from a non existing position the bot will crash;

ever.js doesn't open for some reason(https://my.mixtape.moe/kvbfor.png)

skip command isn't working(https://my.mixtape.moe/cvnrng.png)

and lastly not an issue but a recommendation of sorts, parsing google links, like https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjwxNTuj6nNAhWDf5AKHZo2BfEQyCkIHjAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DPX9JdSox60o&usg=AFQjCNF3qE92akrEQC_G2ZCRw1ZWqU6j1A&sig2=4O1orKYwJa0L2LcNVg1YTg&bvm=bv.124272578,d.dmo

yeah, that's it. Great bot and other than the issues listed there's nothing to complain :^)

**Comment by Brayzure** [comment]
Hello, and thanks for the feedback! Glad you like the bot in its current state.

_When you try removing something from a non existing position the bot will crash._
Forgot to add a safeguard for that. Should be fixed.

_ever.js doesn't open for some reason_
I made a really silly mistake and forgot to include forever-monitor on the list of dependencies.

_skip command isn't working_
Okay that one is a little odd. I'll have to take a look at it. That message should only fire if you're not in the same channel as the bot. !forceskip should ignore that requirement.

_parsing google links_
I've actually been meaning to add that, I'll see if I can manage that.

Again, thank you for the valuable feedback. If you have any more issues to report, or feedback, feel free to let me know!

**Comment by otaviomad** [comment]
Also this https://my.mixtape.moe/rbjtiv.png

**Comment by Brayzure** [comment]
Ohh that's another bug I forgot to fix. It doesn't return any results if the url contains playlist info (which is silly). I'll fix it real quick.

**Comment by Brayzure** [comment]
Pushed an update that _should_ fix it.

**Comment by otaviomad** [comment]
awesome, I'll try it out tomorrow

also, since I'm at it, feedback for when you change the volume would be nice, and I don't remember now, but if it isn't there yet, showing how long the current and queued songs are, and the progress of the current would make this the best bot 

hope I'm not annoying, I know how it is when people nitpick on your work, good luck :^)

**Comment by Brayzure** [comment]
You're not annoying. On the contrary, I love the feedback!

I can add feedback for setting volume, and to top it off, I'll also add a command to check the current volume (so you don't accidentally break everyone's ears). Integrating video duration shouldn't be a major stretch, and it's something I've had my eye on for a while.

**Comment by otaviomad** [comment]
you're pretty cool. I'll update it tomorrow as soon as I wake up

**Comment by otaviomad** [comment]
I promise this is the last but, bandcamp and soundcloud support pretty please? :^)

**Comment by Brayzure** [comment]
Support for those will come later on down the line, I want to get everything else working smoothly first.

**Comment by Brayzure** [comment]
Closing because this will be added in the next update (which will be a total rewrite with new features).
